[tool.poetry]
name = "flake8-awesome"
version = "0.2.0"
description = "Flake8 awesome plugins pack"
authors = ["Afonasev Evgeniy <ea.afonasev@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/afonasev/flake8-awesome"
homepage = "https://pypi.org/project/flake8-awesome"
keywords = ['flake8', 'plugin']

[tool.poetry.dependencies]
python = "^3.6"
flake8 = "^3.7"
flake8-builtins = "^1.4"
flake8-comprehensions = "^1.4"
flake8-eradicate = "^0.2.0"
flake8-if-expr = "^0.2.1"
flake8-isort = "^2.6"
flake8-logging-format = "^0.6.0"
flake8-pytest = "^1.3"
flake8-return = "^0.3.0"
pep8-naming = "^0.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
